services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: rentascortas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 6KeVSs4JKn9E2qsu2akA
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=rentascortas;Username=postgres;Password=6KeVSs4JKn9E2qsu2akA

volumes:
  pgdata: